"""item, quantity added to Order table

Revision ID: 7dd4179c8cb1
Revises: 5dc63b647316
Create Date: 2026-05-02 00:02:12.914328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd4179c8cb1'
down_revision: Union[str, Sequence[str], None] = '5dc63b647316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'item_id')
    # ### end Alembic commands ###
